# Description of what this change includes: corrected several syntax and structural errors within the CloudFormation template. This includes fixing a spelling error in the Resources section and updating the AWSTemplateFormatVersion to the mandatory 2010-09-09 string. Also standardized the Resource Types to use double colons (::) and adjusted the BucketPolicy indentation to ensure it is a child of the Resources block. Finally, the BucketPolicy type was uncommented to allow for active resource provisioning.
# Revision number: 2
# Date: 02/15/26

AWSTemplateFormatVersion: 2019-09-09
Resorces:
  S3Bucket:
    Type: 'AWS:S3:Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
BucketPolicy:
    #Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket
Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content